<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Laia Garcia-Verellen">
<meta name="dcterms.date" content="2025-12-09">

<title>My project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-6a8e6d95bfcd174082ff54166b04dcf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data preparation</a></li>
  <li><a href="#derived-variables-and-aggregation" id="toc-derived-variables-and-aggregation" class="nav-link" data-scroll-target="#derived-variables-and-aggregation">Derived variables and aggregation</a></li>
  <li><a href="#summary-statistics-table" id="toc-summary-statistics-table" class="nav-link" data-scroll-target="#summary-statistics-table">Summary statistics table</a></li>
  <li><a href="#reshaping-the-water-service-quality-index-to-long-format" id="toc-reshaping-the-water-service-quality-index-to-long-format" class="nav-link" data-scroll-target="#reshaping-the-water-service-quality-index-to-long-format">Reshaping the water service quality index to long format</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#temporal-patterns-in-suspected-cholera-admissions" id="toc-temporal-patterns-in-suspected-cholera-admissions" class="nav-link" data-scroll-target="#temporal-patterns-in-suspected-cholera-admissions">Temporal patterns in suspected cholera admissions</a></li>
  <li><a href="#temporal-patterns-in-rdt-positivity" id="toc-temporal-patterns-in-rdt-positivity" class="nav-link" data-scroll-target="#temporal-patterns-in-rdt-positivity">Temporal patterns in RDT positivity</a></li>
  <li><a href="#spatial-heterogeneity-by-cluster" id="toc-spatial-heterogeneity-by-cluster" class="nav-link" data-scroll-target="#spatial-heterogeneity-by-cluster">Spatial heterogeneity by cluster</a></li>
  <li><a href="#treatment-outcomes" id="toc-treatment-outcomes" class="nav-link" data-scroll-target="#treatment-outcomes">Treatment outcomes</a></li>
  <li><a href="#cholera-admissions-in-relation-to-water-service-quality-and-continuity" id="toc-cholera-admissions-in-relation-to-water-service-quality-and-continuity" class="nav-link" data-scroll-target="#cholera-admissions-in-relation-to-water-service-quality-and-continuity">Cholera admissions in relation to water service quality and continuity</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">My project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Laia Garcia-Verellen </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 9, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This report is the capstone project for the <a href="https://ds4owd-002.github.io/website/">DS4OWD-002 course</a> and applies the skills learned in data management and visualisation to a real-world cholera surveillance dataset. This project uses clinical surveillance data from a pragmatic trial conducted in Uvira, Democratic Republic of the Congo, between 2017 and 2021 <span class="citation" data-cites="Gallandat2024">(<a href="#ref-Gallandat2024" role="doc-biblioref">Gallandat 2024</a>)</span>. The trial evaluated the impact of improved piped water infrastructure on cholera and diarrhoeal disease incidence in an urban, cholera-endemic setting.</p>
<p>One of the datasets analysed here contains individual-level records for 4,556 admissions for acute watery diarrhoea at the cholera treatment centre in Uvira. For each admission, key variables include age, sex, date of admission, residential cluster, rapid diagnostic test (RDT) result, treatment outcome, and trial time indicators. In addition, two related datasets extracted from other sheets of the same Excel workbook provide monthly, cluster-level indicators of piped water service quality and a city-wide measure of water service continuity.</p>
<p>The main objective of this analysis is to describe temporal and spatial patterns in suspected and RDT-confirmed cholera cases in Uvira over the period 2017–2021, as well as to explore how these patterns relate to indicators of piped water service quality and continuity. The analysis focuses on monthly trends in suspected admissions and RDT positivity, heterogeneity between residential clusters, and simple visual comparisons with water service quality and continuity indicators, as a first step towards understanding potential impacts of improvements in piped water services on cholera risk.</p>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<section id="data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation">Data preparation</h2>
<p>To ensure a transparent and reproducible workflow, the analysis followed recommended data-management practices (<a href="https://ds4owd-002.github.io/website/">this course</a>, <span class="citation" data-cites="wilson2017">Wilson (<a href="#ref-wilson2017" role="doc-biblioref">2017</a>)</span>, <a href="https://r4ds.had.co.nz/index.html">R for Data Science</a>). The raw data were preserved exactly as received and kept in a dedicated directory without modification. All subsequent processing steps were performed on a copy of the raw file, ensuring that the original data remain intact and permanently accessible. The raw data files were also stored in more than one location to provide additional security <a href="https://github.com/ds4owd-002/project-laigarve">GitHub repository</a>.</p>
<p>Thus, the data analysed in this report is stored as a xlsx file in the <code>data/processed</code> directory. All analyses were conducted in R within Posit Cloud, using the <code>tidyverse</code> framework for data manipulation and visualisation.</p>
<p>The analysis was conducted in R using the <code>readxl</code>, <code>janitor</code>, and <code>tidyverse</code> (<code>lubridate</code>, <code>purrr</code>, <code>ggplot2</code>, <code>tidyr</code>, <code>forcats</code>…) packages for data import, cleaning, manipulation, and visualisation.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)    <span class="co"># import Excel file</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)   <span class="co"># clean variable names</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># data manipulation, exploration and visualization </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Data were imported from the <code>data/raw</code> directory and stored as an object named <code>clinical_raw</code> (clinical surveillance data), <code>index_raw</code> (quality index of the water), and <code>continuity_raw</code> (average proportion of daily hours during which pumps were functioning at the water treatment and pumping station).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>clinical_raw <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"/cloud/project/data/raw/Dataset_2017-2021_OSF.xlsx"</span>), <span class="at">sheet =</span> <span class="dv">2</span>) <span class="co"># use the second sheet, where clinical surveillance data are stored</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>index_raw <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"/cloud/project/data/raw/Dataset_2017-2021_OSF.xlsx"</span>), <span class="at">sheet =</span> <span class="dv">4</span>) <span class="co"># use the fourth sheet, where quality water data are stored</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>continuity_raw <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"/cloud/project/data/raw/Dataset_2017-2021_OSF.xlsx"</span>), <span class="at">sheet =</span> <span class="dv">7</span>) <span class="co"># use the seventh sheet, where average proportion of daily hours during which pumps were functioning at the water treatment and pumping station</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>And each imported object was briefly inspected using to verify the structure and variable types:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>datasets_raw <span class="ot">&lt;-</span> <span class="fu">list</span>( <span class="co"># all datasets stored in a list</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">clinical_raw   =</span> clinical_raw,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">index_raw   =</span> index_raw,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">continuity_raw =</span> continuity_raw)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(datasets_raw) <span class="co"># check column names and types of each dataset</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>List of 3
 $ clinical_raw  : tibble [4,559 × 11] (S3: tbl_df/tbl/data.frame)
  ..$ id        : num [1:4559] 11065 11066 11067 11068 11069 ...
  ..$ date_admit: POSIXct[1:4559], format: "2017-01-01" "2017-01-01" ...
  ..$ age       : num [1:4559] 67 39 3 3 24 ...
  ..$ sex       : chr [1:4559] "F" "F" "F" "M" ...
  ..$ cluster   : num [1:4559] 14 9 11 9 16 6 11 10 11 11 ...
  ..$ confirmed : chr [1:4559] "FALSE" "FALSE" "FALSE" "FALSE" ...
  ..$ outcome   : chr [1:4559] "NA" "NA" "discharged" "discharged" ...
  ..$ month     : num [1:4559] 1 1 1 1 1 1 1 1 1 1 ...
  ..$ year      : num [1:4559] 2017 2017 2017 2017 2017 ...
  ..$ trial_time: logi [1:4559] FALSE FALSE FALSE FALSE FALSE FALSE ...
  ..$ ctc       : chr [1:4559] "ctc" "ctc" "ctc" "ctc" ...
 $ index_raw     : tibble [60 × 17] (S3: tbl_df/tbl/data.frame)
  ..$ Month: POSIXct[1:60], format: "2017-01-01" "2017-02-01" ...
  ..$ 1    : num [1:60] 7.68 6.76 7.68 7.68 6.72 ...
  ..$ 2    : num [1:60] 15.6 15.6 15.6 15.6 15.6 ...
  ..$ 3    : num [1:60] 21.4 20.6 20.6 20.5 20.8 ...
  ..$ 4    : num [1:60] 9.29 9.29 9.29 9.29 9.29 ...
  ..$ 5    : num [1:60] 6.72 6.72 6.72 6.72 6.72 ...
  ..$ 6    : num [1:60] 13.5 13.5 13.5 13.5 13.5 ...
  ..$ 7    : num [1:60] 25 25 25 25 25 25 25 25 25 25 ...
  ..$ 8    : num [1:60] 23.9 23.9 23.9 23.9 23.9 ...
  ..$ 9    : num [1:60] 25 25 25 25 25 25 25 25 25 25 ...
  ..$ 10   : num [1:60] 38.1 37.5 33.3 33.3 32.6 ...
  ..$ 11   : num [1:60] 24 23.7 23.8 23.5 23.6 ...
  ..$ 12   : num [1:60] 10.28 10.15 10.28 6.88 6.88 ...
  ..$ 13   : num [1:60] 29.7 29.9 30 29.8 29.7 ...
  ..$ 14   : num [1:60] 8.76 8.76 8.76 8.76 8.76 ...
  ..$ 15   : num [1:60] 18.9 18.9 18.9 18.9 18.9 ...
  ..$ 16   : num [1:60] 6.72 6.72 6.72 6.72 6.72 ...
 $ continuity_raw: tibble [60 × 2] (S3: tbl_df/tbl/data.frame)
  ..$ Month                    : POSIXct[1:60], format: "2017-01-01" "2017-02-01" ...
  ..$ All clusters (city-level): num [1:60] 65.3 60.4 59.7 61.5 60.6 ...</code></pre>
</div>
</div>
<p>Next, the raw clinical dataset (<code>clinical_raw)</code> was transformed into a processed analysis-friendly format. This included applying clear and consistent variable names and replacing arbitrary missing-value codes with standard NA representations. All data-cleaning and transformation steps were executed through scripted procedures (with each line of code accompanied by a brief comment explaining its purpose), documenting the actions taken, and ensuring that the full data-preparation pipeline can be rerun, inspected, or adapted.</p>
<p>The <code>clinical_raw</code> data were first imported from the original Excel workbook stored in the <code>data/raw</code> directory and processed to create an analysis-ready dataset. Variable types were standardised (e.g.&nbsp;dates, numeric values, and categorical factors), and records with missing cluster, year, or admission date were removed. This resulted in a minimally cleaned dataset saved as <code>clinical_processed</code>, resulting in 4,556 complete observations.</p>
<p>The RDT confirmation variable (<code>confirmed</code>) was recoded from the original character values (“TRUE”, “FALSE”, and missing) into a binary indicator (1 = RDT positive, 0 = RDT negative, <code>NA</code> = not tested). The treatment outcome variable (<code>outcome</code>) was converted to a categorical factor corresponding to discharge status, treatment refusal, transfer, and death.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>clinical_processed <span class="ot">&lt;-</span> clinical_raw <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>() <span class="sc">|&gt;</span>              <span class="co"># ensure safe, consistent column names, more info here: https://cran.r-project.org/web/packages/janitor/vignettes/janitor.html</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">id =</span> <span class="fu">as.character</span>(id),               <span class="co"># keep id as character (not numeric)</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_admit =</span> <span class="fu">as.Date</span>(date_admit),    <span class="co"># ensure admission date is a Date</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">age =</span> <span class="fu">as.numeric</span>(age),               <span class="co"># age as numeric</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">factor</span>(sex),                   <span class="co"># sex as factor (F/M)</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">cluster =</span> <span class="fu">as.integer</span>(cluster),       <span class="co"># cluster as integer ID</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">confirmed =</span> dplyr<span class="sc">::</span><span class="fu">case_when</span>(confirmed <span class="sc">==</span> <span class="st">"TRUE"</span> <span class="sc">~</span> <span class="dv">1</span>L, </span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                                 confirmed <span class="sc">==</span> <span class="st">"FALSE"</span> <span class="sc">~</span> <span class="dv">0</span>L, </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>                                 <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_integer_</span>),    <span class="co"># anything unexpected -&gt; NA</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">as.integer</span>(month),           <span class="co"># month as integer</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">as.integer</span>(year),             <span class="co"># year as integer</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">trial_time =</span> <span class="fu">as.numeric</span>(trial_time), <span class="co"># trial time as numeric</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">ctc =</span> <span class="fu">factor</span>(ctc),                   <span class="co"># ctc as factor</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome =</span> <span class="fu">na_if</span>(outcome, <span class="st">"NA"</span>),      <span class="co"># NA in outcome as a character</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome =</span> <span class="fu">factor</span>(outcome),           <span class="co"># outcome as a factor</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome =</span> forcats<span class="sc">::</span><span class="fu">fct_recode</span>(       <span class="co"># rename for readable purposes</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>      outcome,</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Death"</span>                 <span class="ot">=</span> <span class="st">"death"</span>,</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Death on arrival"</span>      <span class="ot">=</span> <span class="st">"death_on_arrival"</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Discharged"</span>            <span class="ot">=</span> <span class="st">"discharged"</span>,</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Left before discharge"</span> <span class="ot">=</span> <span class="st">"left_before_discharged"</span>,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Transferred"</span>           <span class="ot">=</span> <span class="st">"transferred"</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome =</span> forcats<span class="sc">::</span><span class="fu">fct_relevel</span>(      <span class="co"># order levels in a meaningful sequence</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>      outcome,</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Discharged"</span>,</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Transferred"</span>,</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Left before discharge"</span>,</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Death"</span>,</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Death on arrival"</span>)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(                                <span class="co"># minimal clean: drop rows missing key info</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(cluster),</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(year),</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(date_admit)</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(clinical_processed)              <span class="co"># quick check of dataset</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,556
Columns: 11
$ id         &lt;chr&gt; "11065", "11066", "11067", "11068", "11069", "11070", "1107…
$ date_admit &lt;date&gt; 2017-01-01, 2017-01-01, 2017-01-02, 2017-01-02, 2017-01-03…
$ age        &lt;dbl&gt; 67.000000, 39.000000, 3.000000, 3.000000, 24.000000, 14.000…
$ sex        &lt;fct&gt; F, F, F, M, F, M, F, M, F, M, M, F, M, F, M, F, F, F, M, M,…
$ cluster    &lt;int&gt; 14, 9, 11, 9, 16, 6, 11, 10, 11, 11, 11, 11, 2, 13, 4, 11, …
$ confirmed  &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA…
$ outcome    &lt;fct&gt; NA, NA, Discharged, Discharged, Discharged, Discharged, Dis…
$ month      &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ year       &lt;int&gt; 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017,…
$ trial_time &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ ctc        &lt;fct&gt; ctc, ctc, ctc, ctc, ctc, ctc, ctc, ctc, ctc, ctc, ctc, ctc,…</code></pre>
</div>
</div>
<p>In parallel, the water service quality index sheet (<code>index_raw</code>) was processed to obtain a monthly, cluster-level indicator. Column names were cleaned, the month column was converted to a Date variable, and auxiliary <code>year</code> and <code>month</code> variables were derived. This resulted in <code>index_processed</code>, a processed dataset with one row per month and cluster-level index values expressed on a 0–100 scale.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>index_processed <span class="ot">&lt;-</span> index_raw <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>() <span class="sc">|&gt;</span>             <span class="co"># digit column names are prefixed with "x" </span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_date =</span> month                  <span class="co"># rename month column to month_date</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_date =</span> <span class="fu">as.Date</span>(month_date),   <span class="co"># ensure month_date is a Date</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">year       =</span> <span class="fu">year</span>(month_date),      <span class="co"># extract year, more info about handling dates here: https://lubridate.tidyverse.org/index.html</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">month      =</span> <span class="fu">month</span>(month_date)      <span class="co"># extract month (1–12)</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(index_processed)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 60
Columns: 19
$ month_date &lt;date&gt; 2017-01-01, 2017-02-01, 2017-03-01, 2017-04-01, 2017-05-01…
$ x1         &lt;dbl&gt; 7.6767, 6.7563, 7.6767, 7.6767, 6.7179, 6.7179, 6.7179, 6.7…
$ x2         &lt;dbl&gt; 15.649, 15.649, 15.649, 15.649, 15.649, 15.649, 15.649, 15.…
$ x3         &lt;dbl&gt; 21.388, 20.612, 20.612, 20.517, 20.767, 21.294, 21.388, 21.…
$ x4         &lt;dbl&gt; 9.2922, 9.2922, 9.2922, 9.2922, 9.2922, 9.2922, 9.2922, 9.2…
$ x5         &lt;dbl&gt; 6.7179, 6.7179, 6.7179, 6.7179, 6.7179, 6.7179, 6.7179, 6.7…
$ x6         &lt;dbl&gt; 13.465, 13.465, 13.465, 13.465, 13.465, 13.465, 13.465, 13.…
$ x7         &lt;dbl&gt; 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,…
$ x8         &lt;dbl&gt; 23.912, 23.912, 23.912, 23.912, 23.912, 23.911, 23.912, 23.…
$ x9         &lt;dbl&gt; 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,…
$ x10        &lt;dbl&gt; 38.087, 37.500, 33.255, 33.255, 32.637, 34.448, 36.306, 32.…
$ x11        &lt;dbl&gt; 23.960, 23.663, 23.848, 23.515, 23.570, 23.809, 23.796, 24.…
$ x12        &lt;dbl&gt; 10.2820, 10.1510, 10.2820, 6.8784, 6.8784, 6.8162, 6.8784, …
$ x13        &lt;dbl&gt; 29.656, 29.940, 30.022, 29.806, 29.656, 30.719, 30.286, 25.…
$ x14        &lt;dbl&gt; 8.7637, 8.7637, 8.7637, 8.7637, 8.7637, 8.7637, 8.7637, 8.7…
$ x15        &lt;dbl&gt; 18.852, 18.852, 18.852, 18.852, 18.852, 18.852, 18.852, 18.…
$ x16        &lt;dbl&gt; 6.7179, 6.7179, 6.7179, 6.7179, 6.7179, 6.7179, 6.7179, 6.7…
$ year       &lt;dbl&gt; 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017,…
$ month      &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7,…</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(index_processed))         <span class="co"># checking if and where the NA are</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>month_date         x1         x2         x3         x4         x5         x6 
         0          3          2          3          3          2          2 
        x7         x8         x9        x10        x11        x12        x13 
         2          3          3          2          2          2          2 
       x14        x15        x16       year      month 
         2          2          2          0          0 </code></pre>
</div>
</div>
<p>The continuity sheet (<code>continuity_raw</code>) was processed in a similar way to derive a city-wide water service continuity indicator. Column names were cleaned, the month column was converted to a Date variable, and <code>year</code> and <code>month</code> variables were added. The continuity variable was explicitly cast to numeric, yielding <code>continuity_processed</code>, a monthly time series of the proportion of daily hours during which pumps were functioning at the main water treatment and pumping station.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>continuity_processed <span class="ot">&lt;-</span> continuity_raw <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>() <span class="sc">|&gt;</span>                     </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_date =</span> month,                         </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">continuity =</span> all_clusters_city_level       </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_date =</span> <span class="fu">as.Date</span>(month_date),          </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">continuity =</span> <span class="fu">as.numeric</span>(continuity),        <span class="co"># ensure continuity is numeric</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">year       =</span> <span class="fu">year</span>(month_date),              </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">month      =</span> <span class="fu">month</span>(month_date)              </span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(continuity_processed)     </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 60
Columns: 4
$ month_date &lt;date&gt; 2017-01-01, 2017-02-01, 2017-03-01, 2017-04-01, 2017-05-01…
$ continuity &lt;dbl&gt; 65.33, 60.35, 59.73, 61.55, 60.65, 58.17, 60.75, 57.78, 55.…
$ year       &lt;dbl&gt; 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017,…
$ month      &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7,…</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(continuity_processed))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>month_date continuity       year      month 
         0          3          0          0 </code></pre>
</div>
</div>
<p>Missing values in the water service indices were not removed at the initial data-processing stage for two main reasons:</p>
<ul>
<li>missing entries in the cluster-level quality index and continuity indicators generally reflect genuine gaps in operational data (e.g.&nbsp;months or clusters without recorded measurements).</li>
<li>removing all rows or columns containing <code>NA</code> would discard months that are still informative for most clusters, or months with valid clinical data but incomplete water service information.</li>
</ul>
<p>Instead, missing values were handled in a context-specific manner at the analysis stage (e.g.&nbsp;restricting joins and figures to observations with non-missing <code>index_value</code> or <code>continuity</code>), thereby preserving as much information as possible without introducing artificial imputation.</p>
<p>Finallly, all processed datasets (<code>clinical_processed</code>, <code>index_processed</code>, and <code>continuity_processed</code>) were then written to the <code>data/processed</code> directory as CSV files to ensure reproducibility and to separate raw from analysis-ready data.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>datasets_processed <span class="ot">&lt;-</span> <span class="fu">list</span>( <span class="co"># List of processed datasets to be saved</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">clinical_processed   =</span> clinical_processed,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">index_processed      =</span> index_processed,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">continuity_processed =</span> continuity_processed</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>purrr<span class="sc">::</span><span class="fu">iwalk</span>(               <span class="co"># write each dataset to data/processed as a separate CSV, more info here: https://purrr.tidyverse.org/index.html</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  datasets_processed,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> readr<span class="sc">::</span><span class="fu">write_csv</span>(</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>      .x,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>      here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/processed"</span>, <span class="fu">paste0</span>(.y, <span class="st">".csv"</span>))</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="derived-variables-and-aggregation" class="level2">
<h2 class="anchored" data-anchor-id="derived-variables-and-aggregation">Derived variables and aggregation</h2>
<p>To address questions about temporal and spatial patterns, the individual-level line list was aggregated to the cluster–month level. For each combination of year, month, and residential cluster, the following quantities were computed: the number of suspected cholera admissions, the number of patients tested with RDT, the number of RDT-positive cases, and the proportion of positive tests (RDT positivity). This aggregation provided a compact time series at cluster level and facilitates visualization of trends and heterogeneity.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>clinical_monthly <span class="ot">&lt;-</span> clinical_processed <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, month, cluster) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_admissions   =</span> <span class="fu">n</span>(),                                       <span class="co"># all suspected cases </span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_tested       =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(confirmed)),                    <span class="co"># patients with RDT done</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_confirmed    =</span> <span class="fu">sum</span>(confirmed <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),         <span class="co"># RDT-positive cases</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">rdt_positivity =</span> <span class="fu">if_else</span>(n_tested <span class="sc">&gt;</span> <span class="dv">0</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>                             n_confirmed <span class="sc">/</span> n_tested, <span class="cn">NA_real_</span>)  <span class="co"># avoid division by 0</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="summary-statistics-table" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics-table">Summary statistics table</h2>
<p>A simple set of summary statistics was calculated to describe overall admissions, testing, and RDT positivity across the study period.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>clinical_summary_table <span class="ot">&lt;-</span> clinical_monthly <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_admissions   =</span> <span class="fu">sum</span>(n_admissions, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),     <span class="co"># total suspected admissions</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_tested       =</span> <span class="fu">sum</span>(n_tested,     <span class="at">na.rm =</span> <span class="cn">TRUE</span>),     <span class="co"># total RDT tested</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_confirmed    =</span> <span class="fu">sum</span>(n_confirmed,  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),     <span class="co"># total RDT confirmed</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">overall_positivity =</span> <span class="fu">round</span>((total_confirmed <span class="sc">/</span> total_tested)<span class="sc">*</span><span class="dv">100</span>, <span class="dv">1</span>) <span class="co"># positivity (%)</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>clinical_summary_table_display <span class="ot">&lt;-</span> clinical_summary_table <span class="sc">|&gt;</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Total admissions"</span>                <span class="ot">=</span> total_admissions, <span class="co"># renaming for readable purposes</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Total tested (RDT)"</span>              <span class="ot">=</span> total_tested,</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Total confirmed (RDT positive)"</span>  <span class="ot">=</span> total_confirmed,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Overall RDT positivity (%)"</span>      <span class="ot">=</span> overall_positivity</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  clinical_summary_table_display,</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">align   =</span> <span class="fu">rep</span>(<span class="st">"c"</span>, <span class="fu">ncol</span>(clinical_summary_table_display))</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Overall summary of suspected admissions, testing, and RDT-confirmed cholera cases (2017–2021).
</figcaption>
<div aria-describedby="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 20%">
<col style="width: 32%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Total admissions</th>
<th style="text-align: center;">Total tested (RDT)</th>
<th style="text-align: center;">Total confirmed (RDT positive)</th>
<th style="text-align: center;">Overall RDT positivity (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">4556</td>
<td style="text-align: center;">3309</td>
<td style="text-align: center;">1503</td>
<td style="text-align: center;">45.4</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="reshaping-the-water-service-quality-index-to-long-format" class="level2">
<h2 class="anchored" data-anchor-id="reshaping-the-water-service-quality-index-to-long-format">Reshaping the water service quality index to long format</h2>
<p>To link the cluster-level water service quality index with the monthly clinical data and facilitate plotting, the processed index dataset was reshaped from wide to long format. In this structure, each row corresponds to a unique combination of month and cluster, with a single column (<code>index_value</code>) containing the water service quality index.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>index_long <span class="ot">&lt;-</span> index_processed <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols      =</span> <span class="fu">starts_with</span>(<span class="st">"x"</span>),        <span class="co"># cluster columns (x1, x2, ...)</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to  =</span> <span class="st">"cluster_raw"</span>,           <span class="co"># original cluster column names</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"index_value"</span>            <span class="co"># water service quality index (0–100)</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Extract numeric cluster ID from names like "x1", "x2", ...</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">cluster     =</span> readr<span class="sc">::</span><span class="fu">parse_number</span>(cluster_raw),</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">index_value =</span> <span class="fu">as.numeric</span>(index_value)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(index_long)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 960
Columns: 6
$ month_date  &lt;date&gt; 2017-01-01, 2017-01-01, 2017-01-01, 2017-01-01, 2017-01-0…
$ year        &lt;dbl&gt; 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017…
$ month       &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2…
$ cluster_raw &lt;chr&gt; "x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10…
$ index_value &lt;dbl&gt; 7.6767, 15.6490, 21.3880, 9.2922, 6.7179, 13.4650, 25.0000…
$ cluster     &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1, …</code></pre>
</div>
</div>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p><a href="#tbl-summary" class="quarto-xref">Table&nbsp;1</a> summarises overall admissions, testing, and RDT-confirmed cholera cases over the study period. Between 2017 and 2021, a total of 4,556 suspected cholera admissions were recorded, of which 3,309 (≈73%) underwent RDT testing. Among those tested, 1,503 were RDT positive, corresponding to an overall RDT positivity of about 45%, indicating that roughly one third of all suspected admissions met the definition of confirmed cholera.</p>
<section id="temporal-patterns-in-suspected-cholera-admissions" class="level2">
<h2 class="anchored" data-anchor-id="temporal-patterns-in-suspected-cholera-admissions">Temporal patterns in suspected cholera admissions</h2>
<p>To describe overall trends in suspected cholera burden, monthly admissions were summed across all clusters. This highlights the timing and magnitude of cholera peaks over the study period.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>clinical_monthly_overall <span class="ot">&lt;-</span> clinical_monthly <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, month) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_admissions =</span> <span class="fu">sum</span>(n_admissions, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)   <span class="co"># total admissions per month</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">date =</span> <span class="fu">as.Date</span>(<span class="fu">paste</span>(year, month, <span class="st">"01"</span>, <span class="at">sep =</span> <span class="st">"-"</span>))  <span class="co"># first day of each month</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> clinical_monthly_overall,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> date,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> n_admissions)) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_date</span>(</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_breaks       =</span> <span class="st">"1 year"</span>,   <span class="co"># labels: one per year</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_labels       =</span> <span class="st">"%Y"</span>,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_minor_breaks =</span> <span class="st">"1 month"</span>   <span class="co"># minor grid/ticks: every month</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Date of admission"</span>,</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of suspected cholera admissions"</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-cases-time" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cases-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-cases-time-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cases-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Monthly suspected cholera admissions in Uvira, 2017–2021.
</figcaption>
</figure>
</div>
</div>
</div>
<p>As shown in <a href="#fig-cases-time" class="quarto-xref">Figure&nbsp;1</a>, suspected cholera admissions vary substantially over time, with distinct peaks and troughs between 2017 and 2021. The series is characterized by several sharp peaks, separated by periods of much lower admission numbers, suggesting strong seasonality or intermittent outbreak dynamics. The marked reduction in suspected cholera admissions during most of 2021 is consistent with several contextual changes reported in Uvira. A mass oral cholera vaccination campaign was implemented in mid and late 2020 with high administrative coverage and moderate-to-high coverage in subsequent household surveys, which is likely to have reduced cholera incidence during the following year. In addition, a second cholera treatment unit opened in 2019, so some patients with acute watery diarrhoea may have sought care outside the facility captured in this line list. Ongoing improvements in piped water supply and a modest increase in the proportion of households using REGIDESO taps may also have contributed to lower transmission, although this analysis is descriptive and cannot establish causality.</p>
</section>
<section id="temporal-patterns-in-rdt-positivity" class="level2">
<h2 class="anchored" data-anchor-id="temporal-patterns-in-rdt-positivity">Temporal patterns in RDT positivity</h2>
<p>To approximate trends in confirmed cholera, RDT positivity was calculated as the proportion of tested patients with a positive RDT result in each month.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>clinical_monthly_overall_pos <span class="ot">&lt;-</span> clinical_monthly <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, month) <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_tested    =</span> <span class="fu">sum</span>(n_tested, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_confirmed =</span> <span class="fu">sum</span>(n_confirmed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">date           =</span> <span class="fu">as.Date</span>(<span class="fu">paste</span>(year, month, <span class="st">"01"</span>, <span class="at">sep =</span> <span class="st">"-"</span>)),</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">rdt_positivity =</span> <span class="fu">if_else</span>(</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>      n_tested <span class="sc">&gt;</span> <span class="dv">0</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>      n_confirmed <span class="sc">/</span> n_tested,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>      <span class="cn">NA_real_</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> clinical_monthly_overall_pos,</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> date,</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> rdt_positivity)) <span class="sc">+</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_date</span>(</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_breaks       =</span> <span class="st">"1 year"</span>,   <span class="co"># labels: one per year</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_labels       =</span> <span class="st">"%Y"</span>,</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_minor_breaks =</span> <span class="st">"1 month"</span>   <span class="co"># minor grid/ticks: every month</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">accuracy =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Date of admission"</span>,</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"RDT positivity (%)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-RDT-time" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-RDT-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-RDT-time-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-RDT-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Monthly cholera RDT positivity in Uvira, 2017–2021.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Monthly cholera RDT positivity in Uvira fluctuated markedly over the study period, typically ranging between about 20% and 60%, with only a few months approaching 0% (<a href="#fig-RDT-time" class="quarto-xref">Figure&nbsp;2</a>). This indicates that, in most months, a substantial proportion of tested patients met the definition of confirmed cholera.</p>
</section>
<section id="spatial-heterogeneity-by-cluster" class="level2">
<h2 class="anchored" data-anchor-id="spatial-heterogeneity-by-cluster">Spatial heterogeneity by cluster</h2>
<p>Because the intervention and water distribution network operate at the cluster (neighbourhood) level, it was important to observe how suspected cholera burden varied between clusters.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>clinical_cluster_total <span class="ot">&lt;-</span> clinical_monthly <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cluster) <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_admissions_total =</span> <span class="fu">sum</span>(n_admissions, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> clinical_cluster_total,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(cluster),</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> n_admissions_total)) <span class="sc">+</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Cluster"</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total suspected cholera admissions (2017–2021)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-cluster" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cluster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-cluster-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cluster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Total suspected cholera admissions by cluster.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-cluster" class="quarto-xref">Figure&nbsp;3</a> indicates substantial variation in total suspected cholera admissions between clusters. A small number of clusters (9, 11,13, 16) account for a disproportionate share of admissions, suggesting that local environmental or infrastructural conditions may concentrate cholera risk in specific neighbourhoods. On the contrary, clusters 7 and 8 hold the lowest number of cholera admissions.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>clinical_monthly <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">date =</span> <span class="fu">as.Date</span>(<span class="fu">paste</span>(year, month, <span class="st">"01"</span>, <span class="at">sep =</span> <span class="st">"-"</span>))</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> n_admissions)) <span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_date</span>(</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_breaks =</span> <span class="st">"1 year"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_labels =</span> <span class="st">"%Y"</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> cluster, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Month of admission"</span>, </span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of suspected admissions"</span>) <span class="sc">+</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="co"># text readable</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-cluster-time" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cluster-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-cluster-time-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cluster-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Monthly suspected cholera admissions by cluster.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure <a href="#fig-cluster-time" class="quarto-xref">Figure&nbsp;4</a> shows that temporal patterns differ across clusters, with some neighborhoods experiencing repeated peaks. In particular, a subset of clusters shows sustained or recurrent transmission, suggesting persistent local risk factors. These patterns are most pronounced in clusters 3, 4, 5, 6, 9, 11, 13, and 16 which show repeated high peaks over multiple years, consistent with sustained or recurrent transmission rather than isolated outbreaks. In contrast, clusters 7 and 8 exhibit low and infrequent admissions, suggesting either genuinely lower risk or possible under-ascertainment. The marked heterogeneity between clusters indicates that cholera risk is highly focal within the study area and that targeted interventions in the high-burden neighbourhoods (particularly cluster 16) could yield gains in reducing overall case burden.</p>
</section>
<section id="treatment-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="treatment-outcomes">Treatment outcomes</h2>
<p>Treatment outcomes were summarised to provide a simple description of clinical severity among admitted patients. As shown in <a href="#fig-treatment" class="quarto-xref">Figure&nbsp;5</a>, most admitted patients were discharged, while a smaller proportion died or were transferred to another hospital unit. These outcome distributions provide additional context for interpreting temporal and spatial patterns in suspected and confirmed cholera cases.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>clinical_outcome_summary <span class="ot">&lt;-</span> clinical_processed <span class="sc">|&gt;</span>  <span class="co"># summary of outcomes with proportions</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(outcome)) <span class="sc">|&gt;</span>                       <span class="co"># exclude cases without defined outcome</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(outcome) <span class="sc">|&gt;</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">prop       =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),         <span class="co"># compute proportion for each outcome</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">prop_label =</span> scales<span class="sc">::</span><span class="fu">percent</span>(prop, <span class="at">accuracy =</span> <span class="dv">1</span>)  <span class="co"># formatted label (e.g. "65%")</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Manual color palette with clinical meaning</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>outcome_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Discharged"</span>             <span class="ot">=</span> <span class="st">"#4CAF50"</span>,  <span class="co"># green (favorable outcome)</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Transferred"</span>            <span class="ot">=</span> <span class="st">"#FFC107"</span>,  <span class="co"># amber (intermediate/uncertain)</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Left before discharge"</span>  <span class="ot">=</span> <span class="st">"#FF9800"</span>,  <span class="co"># orange (risk)</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Death"</span>                  <span class="ot">=</span> <span class="st">"#D32F2F"</span>,  <span class="co"># red (severe outcome)</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Death on arrival"</span>       <span class="ot">=</span> <span class="st">"#B71C1C"</span>   <span class="co"># darker red (most severe)</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> clinical_outcome_summary,</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">x    =</span> outcome,</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">y    =</span> prop,</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> outcome</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> prop_label),            <span class="co"># show percentage label above each bar</span></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>,                       <span class="co"># vertical offset above bar</span></span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">size  =</span> <span class="dv">3</span>                           <span class="co"># text size</span></span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">accuracy =</span> <span class="dv">1</span>),</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.1</span>))  <span class="co"># add headroom for labels above bars</span></span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> outcome_cols,</span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">name   =</span> <span class="st">"Treatment outcome"</span></span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Treatment outcome"</span>,</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion of admissions"</span></span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-treatment" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-treatment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-treatment-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-treatment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Distribution of treatment outcomes among cholera admissions.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="cholera-admissions-in-relation-to-water-service-quality-and-continuity" class="level2">
<h2 class="anchored" data-anchor-id="cholera-admissions-in-relation-to-water-service-quality-and-continuity">Cholera admissions in relation to water service quality and continuity</h2>
<p>After examining the spatial distribution of suspected cholera admissions by cluster, an exploratory analysis was undertaken to assess whether clusters with lower cholera burden tended to coincide with higher values of the piped water service quality index. The aim was not to establish causality, but to explore whether any clear visual pattern could be observed between monthly admissions and water service quality across neighborhoods.</p>
<p><a href="#fig-index" class="quarto-xref">Figure&nbsp;6</a> shows the relationship between the monthly water service quality index and suspected cholera admissions across clusters. In most clusters, admissions occur over a relatively narrow range of index values and no clear monotonic association is evident, although some high-burden clusters (4, 5, 6, 14, 16) show higher admissions at lower index values. Other clusters (e.g.&nbsp;3, 9, 11, 13) continue to experience substantial numbers of admissions even at high index values above 20%, indicating that improvements in this service quality indicator alone are not sufficient to eliminate cholera risk. Overall, this exploratory visual analysis does not support a simple linear or threshold relationship between the index and cholera admissions, and no causal conclusions can be drawn from these descriptive data.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>clinical_with_index <span class="ot">&lt;-</span> clinical_monthly <span class="sc">|&gt;</span>   <span class="co"># joining monthly clinical admissions with the water service quality index</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    index_long <span class="sc">|&gt;</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(year, month, cluster, index_value),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"month"</span>, <span class="st">"cluster"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(index_value)                      <span class="co"># NA values are removed </span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> clinical_with_index,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> index_value,                          <span class="co"># water service quality index </span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> n_admissions                          <span class="co"># number of suspected admissions</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span>                   <span class="co"># points with some transparency</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"loess"</span>,</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">se     =</span> <span class="cn">FALSE</span></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span>                                       <span class="co"># smooth trend line</span></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> cluster, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span>  <span class="co"># one panel per cluster</span></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Water service quality index (0–100%)"</span>,</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of suspected cholera admissions per month"</span></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-index" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-index-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-index-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-index-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Relationship between water service quality and monthly cholera admissions by cluster
</figcaption>
</figure>
</div>
</div>
</div>
<p>To compare monthly suspected cholera admissions across quartiles of the water service quality index, <a href="#fig-clinical-with-index" class="quarto-xref">Figure&nbsp;7</a> shows that median admissions are relatively similar across categories, with substantial overlap between interquartile ranges. This suggests no clear graded decrease in admissions with higher index values. Months classified in the “High” category include both low and high admission counts, indicating that, in these data, higher values of the index are not consistently associated with lower cholera burden. No simple dose–response relationship can be inferred from this exploratory comparison.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>clinical_with_index_cat <span class="ot">&lt;-</span> clinical_with_index <span class="sc">|&gt;</span> <span class="co"># Create index categories (quartiles)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">index_cat =</span> <span class="fu">cut</span>(</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>      index_value,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">breaks =</span> <span class="fu">quantile</span>(index_value, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">include.lowest =</span> <span class="cn">TRUE</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Very low"</span>, <span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> clinical_with_index_cat,</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> index_cat,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> n_admissions</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Water service quality index category"</span>,</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Monthly suspected cholera admissions"</span></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-clinical-with-index" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clinical-with-index-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-clinical-with-index-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clinical-with-index-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Monthly cholera admissions by water service quality category
</figcaption>
</figure>
</div>
</div>
</div>
<p>Lastly, <a href="#fig-cont" class="quarto-xref">Figure&nbsp;8</a> shows the relationship between monthly continuity of piped water service and the total number of suspected cholera admissions. Overall, there is no clear linear association: high admission counts are observed across a wide range of continuity values. The loess curve suggests a modest decline in admissions between roughly 55% and 65% continuity, but admissions remain highly variable at all levels, and several months with relatively high continuity still coincide with substantial cholera burden. These descriptive patterns do not support a simple dose–response relationship between continuity and cholera admissions, and no causal interpretation can be drawn from this exploratory analysis.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>clinical_overall_with_cont <span class="ot">&lt;-</span> clinical_monthly_overall <span class="sc">|&gt;</span> <span class="co"># joining overall monthly admissions with the continuity indicator</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    continuity_processed <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(year, month, continuity),    <span class="co"># join on year and month</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"month"</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(continuity)                  </span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> clinical_overall_with_cont,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> continuity,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> n_admissions</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"loess"</span>, <span class="co"># more info here https://r-statistics.co/Loess-Regression-With-R.html</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">se     =</span> <span class="cn">FALSE</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Continuity of water service (% of daily hours with functioning pumps)"</span>,</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Total monthly suspected cholera admissions"</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-cont" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-cont-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Monthly suspected cholera admissions vs water service continuity
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="conclusions" class="level1">
<h1>Conclusions</h1>
<ul>
<li><p><strong>Burden and positivity.</strong> From 2017–2021, 4,556 suspected cholera admissions were recorded, about three quarters were RDT-tested, and ≈45% of those tested were positive, indicating a substantial confirmed cholera burden.</p></li>
<li><p><strong>Temporal and spatial variation.</strong> Admissions showed clear peaks and troughs over time and were highly concentrated in a few clusters (especially 9, 11, 13, and 16), while others (7 and 8) had very few cases, consistent with focal transmission.</p></li>
<li><p><strong>Treatment outcomes.</strong> Most admitted patients were discharged, and deaths or transfers represented a small proportion of recorded outcomes, suggesting substantial morbidity but relatively low recorded in-facility mortality in these data.</p></li>
<li><p><strong>Water indicators and cholera burden.</strong> Simple visual comparisons did <strong>not</strong> show a clear monotonic or dose–response relationship between piped water service quality/continuity and cholera admissions; high case counts occurred across a wide range of index and continuity values.</p></li>
<li><p><strong>Interpretation and limits.</strong> This is a purely descriptive, visually based analysis and cannot establish or exclude causal effects of water supply improvements. These findings should therefore be interpreted alongside the original trial results <span class="citation" data-cites="Gallandat2024">(<a href="#ref-Gallandat2024" role="doc-biblioref">Gallandat 2024</a>)</span>, where formal modelling did identify inverse associations between water service quality/continuity and cholera incidence.</p></li>
</ul>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Gallandat2024" class="csl-entry" role="listitem">
Gallandat, Amy AND Jeandron, Karin AND Macdougall. 2024. <span>“Improved Water Supply Infrastructure to Reduce Acute Diarrhoeal Diseases and Cholera in Uvira, Democratic Republic of the Congo: Results and Lessons Learned from a Pragmatic Trial.”</span> <em>PLOS Neglected Tropical Diseases</em> 18 (7): 1–15. <a href="https://doi.org/10.1371/journal.pntd.0012265">https://doi.org/10.1371/journal.pntd.0012265</a>.
</div>
<div id="ref-wilson2017" class="csl-entry" role="listitem">
Wilson, Jennifer AND Cranston, Greg AND Bryan. 2017. <span>“Good Enough Practices in Scientific Computing.”</span> <em>PLOS Computational Biology</em> 13 (6): 1–20. <a href="https://doi.org/10.1371/journal.pcbi.1005510">https://doi.org/10.1371/journal.pcbi.1005510</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>